# Generated by Django 4.0.5 on 2022-06-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('di', 'Dinheiro'), ('de', 'Débito'), ('cr', 'Crédito'), ('pix', 'Pix'), ('dep', 'Depósito')], default='di', max_length=3, verbose_name='tipo de pagamento')),
                ('paid', models.BooleanField(default=False, verbose_name='pago?')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='preço')),
                ('comission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='comissão')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantidade')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='preço')),
                ('comission_employee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='comissão')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.employee', verbose_name='funcionário')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.order', verbose_name='ordem')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
