# Generated by Django 4.0.5 on 2022-06-05 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='telefone')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='cargo')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ('user__first_name',),
            },
        ),
    ]
