# Generated by Django 4.0.5 on 2022-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='cargo'),
        ),
    ]
