# Generated by Django 4.0.5 on 2022-06-05 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='data de pagamento')),
                ('paid', models.BooleanField(default=False, verbose_name='pago?')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.employee', verbose_name='funcionário')),
            ],
            options={
                'verbose_name': 'Nota de Comissão',
                'verbose_name_plural': 'Notas de Comissão',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ComissionNoteItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True, verbose_name='quantidade')),
                ('comission', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='valor da comissão')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('comission_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.comissionnote', verbose_name='nota de comissão')),
                ('order_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.orderitems', verbose_name='itens do pedido')),
            ],
            options={
                'verbose_name': 'Item da Nota de Comissão',
                'verbose_name_plural': 'Itens da Nota de Comissão',
                'ordering': ('comission_note', 'pk'),
            },
        ),
    ]
