# Generated by Django 4.0.5 on 2022-06-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissionnote',
            name='payment_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='data de pagamento'),
        ),
    ]
